# Site settings
title: Chris Martin
description: "Fluent, Nix, Scala, Haskell, complaining"
baseurl: ""
url: "http://chris-martin.org"
email: ch.martin@gmail.com
twitter_username: chris__martin
github_username: chris-martin
stackoverflow_userid: 402884
googleplus_userid: 102949496905033075906
facebook_username: ch.martin

# Build settings
markdown: kramdown
permalink: /:year/:title
timezone: UTC

excerpt_separator: ""   # Workaround for http://blog.slaks.net/2013-08-09/jekyll-tag-was-never-closed

gems:
  - jekyll-redirect-from
