name: chris-martin-org
version: 0.1.0.0
license: Apache-2.0
github: chris-martin/chris-martin.org

ghc-options: -Wall

library:
  source-dirs: src
  exposed-modules:
    - ChrisMartinOrg
    - ChrisMartinOrg.Content
    - ChrisMartinOrg.Content.Parse
    - ChrisMartinOrg.Core
    - ChrisMartinOrg.Css
    - ChrisMartinOrg.Hash
    - ChrisMartinOrg.Home
    - ChrisMartinOrg.Post
    - ChrisMartinOrg.PostDate
    - ChrisMartinOrg.Post.Page
    - ChrisMartinOrg.Post.Parse
    - ChrisMartinOrg.Redirect
    - ChrisMartinOrg.RSS

dependencies:
  - base
  - attoparsec
  - blaze-html
  - blaze-markup
  - bytestring
  - containers
  - cryptonite
  - directory
  - filepath
  - highlighting-kate
  - hsass
  - markdown
  - network-uri
  - rss
  - safe
  - text
  - time
  - unix

executables:
  site:
    source-dirs: app
    main: Main.hs
    dependencies:
      - chris-martin-org

tests:
  test:
    source-dirs: test
    main: test.hs
    dependencies:
      - base
      - HUnit
      - test-framework
      - test-framework-hunit
      - doctest
